modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/murqin/NoCropTrample/issues"

[[mods]]
modId = "nocroptrample"
version = "${version}"
displayName = "NoCropTrample"
description = "Prevents farmland from being trampled by players and mobs"
authors = "Murqin"
displayURL = "https://github.com/murqin/NoCropTrample"
iconFile = "nocroptrample:icon.png"

[[dependencies.nocroptrample]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.6,21.11)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.nocroptrample]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.6,1.21.10]"
    ordering = "NONE"
    side = "BOTH"
